name: pgvector
services:
  pgvector:
    image: pgvector/pgvector:pg17
    container_name: pgvector-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vectordb
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgvector_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    networks:
      - rag_network

volumes:
  pgvector_data:
    name: pgvector_data

networks:
  rag_network:
    name: rag_network 